version: '3.9'
services:
  app:
    build:
      context: ../app
      dockerfile: devDockerfile
    ports:
      - 4000:4000
    volumes:
      - ../app:/opt/app

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bookshelf
    ports:
      - 5432:5432
